name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  add_reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add branch owner as a reviewer
        uses: cirrus-actions/reviewers@v1
        with:
          reviewers: ${{ github.actor }} # Automatically adds the branch owner
