name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint_and_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'

  # deploy_to_netlify:
  #   runs-on: ubuntu-latest
  #   needs: lint_and_tests # This job will run only if "lint_and_tests" succeeds
  #   steps:
  #     - name: Trigger Netlify Deploy
  #       run: curl -X POST -d '{}' "${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}"
