jobs:
  lint_and_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

  deploy_to_netlify:
    runs-on: ubuntu-latest
    needs: lint_and_tests
    if: success() # This ensures the deploy step runs only if lint_and_tests succeed
    steps:
      - name: Trigger Netlify Deploy
        run: curl -X POST -d '{}' "${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}"
