# name: CI workflow
# on: push

# jobs:
#   run-linter-and-tests:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: npm install
#         run: npm i

#       - name: Lint code
#         run: npm run lint

#       - name: Run tests
#         run: npm test

name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint_and_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

  deploy_to_netlify:
    runs-on: ubuntu-latest
    needs: lint_and_tests # This job will run only if "lint_and_test" succeeds
    steps:
      - name: Trigger Netlify Deploy
        run: curl -X POST -d {} "<NETLIFY_DEPLOY_HOOK_URL>"
        env:
          NETLIFY_DEPLOY_HOOK_URL: ${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}
