name: Pipeline - Pull Request Workflow

on:
  push:
    # branches-ignore: # Trigger the workflow for pushes to any branch except 'main'
    #   - main

jobs:
  lint_and_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run formatter
        run: npm run format:fix

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test
